<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        function fn1() {
            return Promise.resolve(1)
        }
        function fn2() {
            return 2
        }
        function fn3() {
            return Promise.reject(3)
            // return fn3.test() // 程序运行会抛出异常
        }
        function fn4() {
            return fn3.test() // 程序运行会抛出异常
        }
        // 没有使用 await 的 async 函数
        async function fn5() {
            return 4
        }
        async function fn() {
            // await 右侧是一个成功的 promise
            // const result = await fn1()
            // console.log('result: ', result)
            // return result + 10

            // await 右侧是一个非 promise 的数据
            const result = await fn2()
            console.log('result: ', result)
            return result + 10

            // await 右侧是一个失败的 promise
            // try {
            //     const result = await fn3()
            // } catch (e) {
            //     console.log(e);
            // }

            // await 右侧抛出异常
            // try {
            //     const result = await fn4()
            // } catch (e) {
            //     console.log(e);
            // }
        }
        // fn()

        async function test() {
            try {
                const result2 = await fn()
                console.log('result2', result2)
            } catch (error) {
                console.log('error', error)
            }
            try {
                const result3 = await fn4()
                console.log('result4', result3)
            } catch (error) {
                console.log('error', error)
            }
        }
        test()
    </script>
</body>

</html>